import { addIcons } from 'ionicons';
import {
  addCircle,
  addCircleOutline,
  analyticsOutline,
  archiveOutline,
  arrowBack,
  arrowForward,
  call,
  cameraOutline,
  cartOutline,
  chatbubbleOutline,
  chatbubblesOutline,
  checkmark,
  chevronBack,
  chevronForward,
  clipboardOutline,
  close,
  closeCircleOutline,
  compassOutline,
  create,
  cubeOutline,
  eye,
  eyeOff,
  heart,
  heartOutline,
  images,
  informationCircleOutline,
  locationOutline,
  logInOutline,
  logOutOutline,
  logoFacebook,
  logoGoogle,
  logoInstagram,
  mail,
  menuOutline,
  moonOutline,
  newspaperOutline,
  notificationsOffOutline,
  notificationsOutline,
  peopleCircleOutline,
  personAddOutline,
  personOutline,
  phonePortraitOutline,
  pricetagsOutline,
  refreshOutline,
  searchOutline,
  send,
  shareSocialOutline,
  shieldCheckmarkOutline,
  starOutline,
  sunnyOutline,
  thumbsDown,
  thumbsDownOutline,
  thumbsUp,
  thumbsUpOutline,
  trash,
  walkOutline,
  warningOutline,
} from 'ionicons/icons';

let registered = false;

/**
 * Registra los iconos que usa la aplicación.
 *
 * Ionic 9 en modo standalone ya no carga el juego completo de iconos: hay que
 * declarar los que se usan. Es más trabajo, pero evita arrastrar al paquete
 * final el millar largo de SVG de la biblioteca cuando sólo hacen falta unas
 * decenas.
 *
 * Se llama desde el componente raíz; las llamadas siguientes no hacen nada.
 */
export function registerAppIcons(): void {
  if (registered) {
    return;
  }

  registered = true;

  addIcons({
    'add-circle': addCircle,
    'add-circle-outline': addCircleOutline,
    'analytics-outline': analyticsOutline,
    'archive-outline': archiveOutline,
    'arrow-back': arrowBack,
    'arrow-forward': arrowForward,
    call,
    'camera-outline': cameraOutline,
    'cart-outline': cartOutline,
    'chatbubble-outline': chatbubbleOutline,
    'chatbubbles-outline': chatbubblesOutline,
    checkmark,
    'chevron-back': chevronBack,
    'chevron-forward': chevronForward,
    'clipboard-outline': clipboardOutline,
    close,
    'close-circle-outline': closeCircleOutline,
    'compass-outline': compassOutline,
    create,
    'cube-outline': cubeOutline,
    eye,
    'eye-off': eyeOff,
    heart,
    'heart-outline': heartOutline,
    images,
    'information-circle-outline': informationCircleOutline,
    'location-outline': locationOutline,
    'log-in-outline': logInOutline,
    'log-out-outline': logOutOutline,
    'logo-facebook': logoFacebook,
    'logo-google': logoGoogle,
    'logo-instagram': logoInstagram,
    mail,
    'menu-outline': menuOutline,
    'moon-outline': moonOutline,
    'newspaper-outline': newspaperOutline,
    'notifications-outline': notificationsOutline,
    'notifications-off-outline': notificationsOffOutline,
    'people-circle-outline': peopleCircleOutline,
    'person-add-outline': personAddOutline,
    'person-outline': personOutline,
    'phone-portrait-outline': phonePortraitOutline,
    'pricetags-outline': pricetagsOutline,
    'refresh-outline': refreshOutline,
    'search-outline': searchOutline,
    send,
    'share-social-outline': shareSocialOutline,
    'shield-checkmark-outline': shieldCheckmarkOutline,
    'star-outline': starOutline,
    'sunny-outline': sunnyOutline,
    'thumbs-down': thumbsDown,
    'thumbs-down-outline': thumbsDownOutline,
    'thumbs-up': thumbsUp,
    'thumbs-up-outline': thumbsUpOutline,
    trash,
    'walk-outline': walkOutline,
    'warning-outline': warningOutline,
  });
}
