import { addIcons } from 'ionicons';
import {
  add,
  addCircle,
  addCircleOutline,
  alertCircle,
  alertCircleOutline,
  analytics,
  analyticsOutline,
  appsOutline,
  archiveOutline,
  arrowBack,
  arrowDown,
  arrowForward,
  arrowRedo,
  arrowRedoOutline,
  arrowUndo,
  arrowUndoOutline,
  at,
  banOutline,
  book,
  bookOutline,
  bookmark,
  bookmarkOutline,
  business,
  calendarOutline,
  camera,
  cameraOutline,
  cameraReverse,
  cart,
  cartOutline,
  chatboxEllipsesOutline,
  chatbubble,
  chatbubbleEllipses,
  chatbubbleEllipsesOutline,
  chatbubbleOutline,
  chatbubbles,
  chatbubblesOutline,
  checkmark,
  checkmarkCircle,
  checkmarkDone,
  chevronBack,
  chevronForward,
  clipboardOutline,
  close,
  closeCircle,
  closeCircleOutline,
  cloudOfflineOutline,
  codeSlash,
  colorPaletteOutline,
  compass,
  compassOutline,
  copy,
  copyOutline,
  create,
  createOutline,
  cube,
  cubeOutline,
  desktopOutline,
  documentLockOutline,
  documentOutline,
  documentText,
  downloadOutline,
  earth,
  ellipsisHorizontal,
  ellipsisVertical,
  exitOutline,
  eye,
  eyeOffOutline,
  flagOutline,
  giftOutline,
  grid,
  handLeftOutline,
  happy,
  happyOutline,
  hardwareChipOutline,
  heart,
  heartOutline,
  helpCircle,
  helpCircleOutline,
  home,
  homeOutline,
  idCardOutline,
  image,
  images,
  imagesOutline,
  informationCircle,
  informationCircleOutline,
  keyOutline,
  language,
  link,
  linkOutline,
  list,
  location,
  locationOutline,
  lockClosed,
  lockClosedOutline,
  logInOutline,
  logOut,
  logOutOutline,
  logoApple,
  logoFacebook,
  logoGoogle,
  logoInstagram,
  mail,
  mailOutline,
  mailUnreadOutline,
  megaphone,
  menu,
  menuOutline,
  mic,
  micOff,
  moon,
  moonOutline,
  newspaperOutline,
  notifications,
  notificationsOff,
  notificationsOffOutline,
  notificationsOutline,
  openOutline,
  pause,
  people,
  peopleCircle,
  peopleCircleOutline,
  personAdd,
  personAddOutline,
  personCircleOutline,
  personOutline,
  personRemoveOutline,
  phonePortraitOutline,
  pin,
  pinOutline,
  play,
  pricetagOutline,
  pricetagsOutline,
  radioButtonOn,
  refreshOutline,
  remove,
  returnDownForward,
  search,
  searchOutline,
  send,
  settings,
  settingsOutline,
  shareSocialOutline,
  shieldCheckmark,
  shieldCheckmarkOutline,
  shieldHalf,
  shieldOutline,
  starOutline,
  storefront,
  storefrontOutline,
  sunny,
  sunnyOutline,
  tabletPortraitOutline,
  thumbsDownOutline,
  thumbsUp,
  thumbsUpOutline,
  time,
  timeOutline,
  trash,
  trashOutline,
  videocam,
  videocamOff,
  videocamOffOutline,
  videocamOutline,
  volumeHigh,
  volumeMute,
  walkOutline,
  warningOutline,
} from 'ionicons/icons';

let registered = false;

/**
 * Registra los iconos que usa la aplicación.
 *
 * Ionic 9 no carga el juego completo de iconos: hay que declarar los que se
 * usan. Es más trabajo, pero evita arrastrar al paquete final el millar largo
 * de SVG de la biblioteca cuando sólo hacen falta unas decenas.
 *
 * Se llama desde el componente raíz; las llamadas siguientes no hacen nada.
 */
export function registerAppIcons(): void {
  if (registered) {
    return;
  }

  registered = true;

  addIcons({
    add,
    'add-circle': addCircle,
    'add-circle-outline': addCircleOutline,
    'alert-circle': alertCircle,
    'alert-circle-outline': alertCircleOutline,
    analytics,
    'analytics-outline': analyticsOutline,
    'apps-outline': appsOutline,
    'archive-outline': archiveOutline,
    'arrow-back': arrowBack,
    'arrow-down': arrowDown,
    'arrow-forward': arrowForward,
    'arrow-redo': arrowRedo,
    'arrow-redo-outline': arrowRedoOutline,
    'arrow-undo': arrowUndo,
    'arrow-undo-outline': arrowUndoOutline,
    at,
    'ban-outline': banOutline,
    book,
    'book-outline': bookOutline,
    bookmark,
    'bookmark-outline': bookmarkOutline,
    business,
    'calendar-outline': calendarOutline,
    camera,
    'camera-outline': cameraOutline,
    'camera-reverse': cameraReverse,
    cart,
    'cart-outline': cartOutline,
    'chatbox-ellipses-outline': chatboxEllipsesOutline,
    chatbubble,
    'chatbubble-ellipses': chatbubbleEllipses,
    'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
    'chatbubble-outline': chatbubbleOutline,
    chatbubbles,
    'chatbubbles-outline': chatbubblesOutline,
    checkmark,
    'checkmark-circle': checkmarkCircle,
    'checkmark-done': checkmarkDone,
    'chevron-back': chevronBack,
    'chevron-forward': chevronForward,
    'clipboard-outline': clipboardOutline,
    close,
    'close-circle': closeCircle,
    'close-circle-outline': closeCircleOutline,
    'cloud-offline-outline': cloudOfflineOutline,
    'code-slash': codeSlash,
    'color-palette-outline': colorPaletteOutline,
    compass,
    'compass-outline': compassOutline,
    copy,
    'copy-outline': copyOutline,
    create,
    'create-outline': createOutline,
    cube,
    'cube-outline': cubeOutline,
    'desktop-outline': desktopOutline,
    'document-lock-outline': documentLockOutline,
    'document-outline': documentOutline,
    'document-text': documentText,
    'download-outline': downloadOutline,
    earth,
    'ellipsis-horizontal': ellipsisHorizontal,
    'ellipsis-vertical': ellipsisVertical,
    'exit-outline': exitOutline,
    eye,
    'eye-off-outline': eyeOffOutline,
    'flag-outline': flagOutline,
    'gift-outline': giftOutline,
    grid,
    'hand-left-outline': handLeftOutline,
    happy,
    'happy-outline': happyOutline,
    'hardware-chip-outline': hardwareChipOutline,
    heart,
    'heart-outline': heartOutline,
    'help-circle': helpCircle,
    'help-circle-outline': helpCircleOutline,
    home,
    'home-outline': homeOutline,
    'id-card-outline': idCardOutline,
    image,
    images,
    'images-outline': imagesOutline,
    'information-circle': informationCircle,
    'information-circle-outline': informationCircleOutline,
    'key-outline': keyOutline,
    language,
    link,
    'link-outline': linkOutline,
    list,
    location,
    'location-outline': locationOutline,
    'lock-closed': lockClosed,
    'lock-closed-outline': lockClosedOutline,
    'log-in-outline': logInOutline,
    'log-out': logOut,
    'log-out-outline': logOutOutline,
    'logo-apple': logoApple,
    'logo-facebook': logoFacebook,
    'logo-google': logoGoogle,
    'logo-instagram': logoInstagram,
    mail,
    'mail-outline': mailOutline,
    'mail-unread-outline': mailUnreadOutline,
    megaphone,
    menu,
    'menu-outline': menuOutline,
    mic,
    'mic-off': micOff,
    moon,
    'moon-outline': moonOutline,
    'newspaper-outline': newspaperOutline,
    notifications,
    'notifications-off': notificationsOff,
    'notifications-off-outline': notificationsOffOutline,
    'notifications-outline': notificationsOutline,
    'open-outline': openOutline,
    pause,
    people,
    'people-circle': peopleCircle,
    'people-circle-outline': peopleCircleOutline,
    'person-add': personAdd,
    'person-add-outline': personAddOutline,
    'person-circle-outline': personCircleOutline,
    'person-outline': personOutline,
    'person-remove-outline': personRemoveOutline,
    'phone-portrait-outline': phonePortraitOutline,
    pin,
    'pin-outline': pinOutline,
    play,
    'pricetag-outline': pricetagOutline,
    'pricetags-outline': pricetagsOutline,
    'radio-button-on': radioButtonOn,
    'refresh-outline': refreshOutline,
    remove,
    'return-down-forward': returnDownForward,
    search,
    'search-outline': searchOutline,
    send,
    settings,
    'settings-outline': settingsOutline,
    'share-social-outline': shareSocialOutline,
    'shield-checkmark': shieldCheckmark,
    'shield-checkmark-outline': shieldCheckmarkOutline,
    'shield-half': shieldHalf,
    'shield-outline': shieldOutline,
    'star-outline': starOutline,
    storefront,
    'storefront-outline': storefrontOutline,
    sunny,
    'sunny-outline': sunnyOutline,
    'tablet-portrait-outline': tabletPortraitOutline,
    'thumbs-down-outline': thumbsDownOutline,
    'thumbs-up': thumbsUp,
    'thumbs-up-outline': thumbsUpOutline,
    time,
    'time-outline': timeOutline,
    trash,
    'trash-outline': trashOutline,
    videocam,
    'videocam-off': videocamOff,
    'videocam-off-outline': videocamOffOutline,
    'videocam-outline': videocamOutline,
    'volume-high': volumeHigh,
    'volume-mute': volumeMute,
    'walk-outline': walkOutline,
    'warning-outline': warningOutline,
  });
}
